if(EXISTS "/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-invariants-b12d07c_tests.cmake")
  include("/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-invariants-b12d07c_tests.cmake")
else()
  add_test(matcher-invariants_NOT_BUILT-b12d07c matcher-invariants_NOT_BUILT-b12d07c)
endif()
