if(EXISTS "/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-corpus-b12d07c_tests.cmake")
  include("/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-corpus-b12d07c_tests.cmake")
else()
  add_test(matcher-corpus_NOT_BUILT-b12d07c matcher-corpus_NOT_BUILT-b12d07c)
endif()
