if(EXISTS "/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-ring-b12d07c_tests.cmake")
  include("/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-ring-b12d07c_tests.cmake")
else()
  add_test(matcher-ring_NOT_BUILT-b12d07c matcher-ring_NOT_BUILT-b12d07c)
endif()
