if(EXISTS "/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-allocation-b12d07c_tests.cmake")
  include("/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-allocation-b12d07c_tests.cmake")
else()
  add_test(matcher-allocation_NOT_BUILT-b12d07c matcher-allocation_NOT_BUILT-b12d07c)
endif()
