if(EXISTS "/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-determinism-b12d07c_tests.cmake")
  include("/Users/louisgrennell/Exchange/build-sanitize/components/matcher/matcher-determinism-b12d07c_tests.cmake")
else()
  add_test(matcher-determinism_NOT_BUILT-b12d07c matcher-determinism_NOT_BUILT-b12d07c)
endif()
