#!/usr/bin/env python3
"""The codegen ritual: the hot path's assembly, read on purpose.

The venue is built for one box, Ice Lake x86-64, so the assembly worth reading is that target's,
whatever machine this runs on. The script compiles a probe translation unit that explicitly
instantiates one matcher partition against a ring that costs nothing, which forces the whole hot
path into named symbols with everything below it inlined in. It then extracts the chosen
functions and reports every call and tail call left inside them, because a call inside the match
loop is either on a list the reader has blessed or a regression worth a diff.

macOS and Linux share the System V AMD64 calling convention, so on a laptop the script targets
the host's own OS with the box's -march and reads the same instruction stream the box runs,
without needing a Linux sysroot.

  scripts/codegen.py [--build build] [--out build/codegen] [--symbol REGEX]
                     [--march icelake-server] [--compiler clang++]

The full assembly and one file per extracted function land in --out. Exit code 0 always: the
ritual informs, and what a gate may assert is decided by the campaign once normal has a number.
"""

import argparse
import pathlib
import re
import subprocess
import sys

# The probe compiles with the release build's own defines, because the ritual must read the
# instruction stream the box runs, bounds-check elision included.
PROBE = """// Generated by scripts/codegen.py: the instantiation the ritual reads. The explicit
// instantiation forces every member of one partition, against a ring that costs nothing, into
// named symbols, so the hot path is readable as one function.
#include <cstddef>

#include "partition.hpp"

class DiscardingRing {
 public:
  std::size_t claim(const std::size_t length) {
    const std::size_t aligned = (length + 7) & ~std::size_t{7};
    if (cursor_ + aligned > sizeof space_) {
      cursor_ = 0;
    }
    const std::size_t at = cursor_;
    cursor_ += aligned;
    return at;
  }
  char* buffer() { return space_; }
  void commit() {}
  void publish() {}

 private:
  char space_[1 << 16] = {};
  std::size_t cursor_ = 0;
};

template class exchange::matcher::Partition<DiscardingRing>;
"""

DIRECTIVE = re.compile(r"^\s*[.;#]")
# A label ends a function only when it opens another; assembler-local labels (LBB branch
# targets, Lfunc/Ltmp markers, .L on Linux) belong to the body they sit in.
LABEL = re.compile(r"^([A-Za-z_$][\w$.]*):")
LOCAL = re.compile(r"^\.?L")
MANGLED = re.compile(r"^_?_Z")


def demangle(names):
    if not names:
        return {}
    # Apple emits mangled names with one extra leading underscore, which c++filt does not expect.
    stripped = [name[1:] if name.startswith("__Z") else name for name in names]
    result = subprocess.run(
        ["c++filt"], input="\n".join(stripped), capture_output=True, text=True, check=True
    )
    return dict(zip(names, result.stdout.splitlines()))


def functions(lines):
    """Every mangled-label function as (label, [body lines]), split on the next label."""
    found = []
    name = None
    body = []
    for line in lines:
        label = LABEL.match(line)
        if label and not LOCAL.match(label.group(1)):
            if name is not None:
                found.append((name, body))
            name, body = (label.group(1), []) if MANGLED.match(label.group(1)) else (None, [])
            continue
        if name is not None:
            body.append(line)
    if name is not None:
        found.append((name, body))
    return found


def instructions(body):
    return [line.strip() for line in body if line.strip() and not DIRECTIVE.match(line)]


def escapes(mnemonic, operand):
    """A control transfer that leaves the function: a call, or a tail call to a real symbol."""
    if mnemonic.startswith("call"):
        return True
    return (mnemonic.startswith("jmp") and bool(re.match(r"^_?[A-Za-z]", operand))
            and not LOCAL.match(operand))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", default="build", help="configured build directory")
    parser.add_argument("--out", default=None, help="where the assembly lands")
    parser.add_argument("--symbol", default="onCommand", help="regex choosing the functions read")
    parser.add_argument("--march", default="icelake-server", help="the box's architecture")
    parser.add_argument("--compiler", default="clang++")
    arguments = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    build = root / arguments.build
    codecs = build / "schema" / "generated"
    if not (codecs / "exchange_protocol" / "MessageHeader.h").exists():
        sys.exit(f"no generated codecs under {codecs}; configure and build first")
    out = pathlib.Path(arguments.out) if arguments.out else build / "codegen"
    out.mkdir(parents=True, exist_ok=True)

    probe = out / "probe.cpp"
    probe.write_text(PROBE)
    assembly = out / "partition.s"
    triple = "x86_64-apple-macos" if sys.platform == "darwin" else "x86_64-linux-gnu"
    subprocess.run(
        [
            arguments.compiler, "-S", "-O3", "-DNDEBUG", "-DSBE_NO_BOUNDS_CHECK",
            "-std=c++23",
            f"-march={arguments.march}", f"--target={triple}",
            "-I", str(root / "components" / "matcher" / "src"),
            "-I", str(root / "components" / "common"),
            "-I", str(codecs),
            "-o", str(assembly), str(probe),
        ],
        check=True,
    )

    lines = assembly.read_text().splitlines()
    every = functions(lines)
    names = demangle([name for name, _ in every])
    wanted = re.compile(arguments.symbol)
    matched = [(name, body) for name, body in every if wanted.search(names[name])]
    if not matched:
        print(f"nothing matched {arguments.symbol!r}; the functions present:")
        for name, _ in every:
            print(f"  {names[name]}")
        return

    # The compiler outlines the throw paths as .cold continuations; they are reported as one
    # line because a refusal that throws is initialisation-grade code, and the reading is about
    # the hot part.
    cold = [(name, body) for name, body in matched if ".cold" in names[name]]
    for at, (name, body) in enumerate(x for x in matched if ".cold" not in names[x[0]]):
        short = re.sub(r"\W+", "-", names[name])[:72].strip("-")
        extract = out / f"{at:02d}-{short}.s"
        extract.write_text("\n".join(body) + "\n")
        listed = instructions(body)
        left = []
        for line in listed:
            parts = line.split(None, 1)
            mnemonic, operand = parts[0], parts[1] if len(parts) > 1 else ""
            if escapes(mnemonic, operand):
                left.append(line)
        print(names[name])
        print(f"  {len(listed)} instructions, extracted to {extract}")
        if left:
            # Aggregated by target with counts, first appearance first: complete, so a real
            # regression cannot hide behind a filter, and short enough to actually read.
            targets = demangle([line.split()[-1] for line in left])
            counts = {}
            for line in left:
                counts[targets[line.split()[-1]]] = counts.get(targets[line.split()[-1]], 0) + 1
            print(f"  {len(left)} escapes:")
            for target, count in counts.items():
                print(f"    {count:3d}  {target}")
        else:
            print("  never leaves the function: no calls, no tail calls")
    if cold:
        total = sum(len(instructions(body)) for _, body in cold)
        print(f"{len(cold)} outlined cold continuations, {total} instructions, the throw paths")


if __name__ == "__main__":
    main()
